version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=hello_java
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/hello_java
      SPRING_DATASOURCE_USERNAME: demo_java
      SPRING_DATASOURCE_PASSWORD: 1234